title: 뇌절
description: 굳이 여기까지 알 필요는 없지만, 재미로 밑바닥까지 파보는 기술 블로그
url: "https://minjune8506.github.io"
baseurl: ""

author:
  name: minjune8506
  email: minjune8506@gmail.com

theme: minima
minima:
  skin: classic
  social_links:
    github: minjune8506

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

future: true

paginate: 8
paginate_path: "/page:num/"

show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
